# Generated by Django 3.1.3 on 2020-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favmovapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
